### ISSUE TITLE
does not execute

### ISSUE THREAD

**Issue by ginnies** [CatherineH/pyHighFinesse#1]
Traceback (most recent call last):
  File "C:\Python27\wavemeter_manager\wlm\scatterplot.py", line 3, in <module>
    reading = specm.Spectrometer()
  File "C:\Python27\wavemeter_manager\wlm\spectrometer.py", line 51, in **init**
    control_show = self.lib.ControlWLM(getattr(self, 'cCtrlWLMShow'), 0, 0)
ValueError: Procedure called with not enough arguments (12 bytes missing) or wrong calling convention

**Comment by CatherineH** [comment]
Hi,

How was this module installed? I am confused about why it is in a wavemeter_manager folder.

**Comment by CatherineH** [comment]
Try changing that line to:

```
control_show = self.lib.ControlWLM(self.cCtrlWLMShow, 0, 0)
```

If that does not work, change it to:

```
control_show = self.lib.ControlWLM(1, 0, 0)
```
